version: "3"
services:
  php:
    build: './.docker/php/'
    networks:
      - backend
    volumes:
      - ./public/:/var/www/html/
  apache:
    build: './.docker/apache/'
    depends_on:
      - php
      - db
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./public/:/var/www/html/
  db:
    image: mariadb:10.4
    networks:
      - backend
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
networks:
  frontend:
  backend: